/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dummy_calc_JavaExprtkAdapter */

#ifndef _Included_org_dummy_calc_JavaExprtkAdapter
#define _Included_org_dummy_calc_JavaExprtkAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dummy_calc_JavaExprtkAdapter
 * Method:    calculateJni
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_dummy_calc_JavaExprtkAdapter_calculateJni
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
