/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dummy_calc_ExprtkAdapter */

#ifndef _Included_org_dummy_calc_ExprtkAdapter
#define _Included_org_dummy_calc_ExprtkAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dummy_calc_ExprtkAdapter
 * Method:    calculate
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_org_dummy_calc_ExprtkAdapter_calculate
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
